INDIAN_STOCKS = [
    {"symbol": "RELIANCE.NS", "name": "Reliance Industries"},
    {"symbol": "TCS.NS", "name": "Tata Consultancy Services"},
    {"symbol": "HDFCBANK.NS", "name": "HDFC Bank"},
    {"symbol": "INFY.NS", "name": "Infosys"},
    {"symbol": "ICICIBANK.NS", "name": "ICICI Bank"},
    {"symbol": "HINDUNILVR.NS", "name": "Hindustan Unilever"},
    {"symbol": "SBIN.NS", "name": "State Bank of India"},
    {"symbol": "BHARTIARTL.NS", "name": "Bharti Airtel"},
    {"symbol": "ITC.NS", "name": "ITC Limited"},
    {"symbol": "KOTAKBANK.NS", "name": "Kotak Mahindra Bank"},
    {"symbol": "LT.NS", "name": "Larsen & Toubro"},
    {"symbol": "AXISBANK.NS", "name": "Axis Bank"},
    {"symbol": "TATAMOTORS.NS", "name": "Tata Motors"},
    {"symbol": "MARUTI.NS", "name": "Maruti Suzuki"},
    {"symbol": "ULTRACEMCO.NS", "name": "UltraTech Cement"},
    {"symbol": "ASIANPAINT.NS", "name": "Asian Paints"},
    {"symbol": "SUNPHARMA.NS", "name": "Sun Pharmaceutical"},
    {"symbol": "TITAN.NS", "name": "Titan Company"},
    {"symbol": "HCLTECH.NS", "name": "HCL Technologies"},
    {"symbol": "BAJFINANCE.NS", "name": "Bajaj Finance"},
    {"symbol": "NTPC.NS", "name": "NTPC Limited"},
    {"symbol": "POWERGRID.NS", "name": "Power Grid Corporation"},
    {"symbol": "TATAFEL.NS", "name": "Tata Steel"},
    {"symbol": "ADANIENT.NS", "name": "Adani Enterprises"},
    {"symbol": "ADANIPORTS.NS", "name": "Adani Ports"},
    {"symbol": "WIPRO.NS", "name": "Wipro"},
    {"symbol": "ONGC.NS", "name": "ONGC"},
    {"symbol": "JSWSTEEL.NS", "name": "JSW Steel"},
    {"symbol": "M&M.NS", "name": "Mahindra & Mahindra"},
    {"symbol": "COALINDIA.NS", "name": "Coal India"},
    {"symbol": "ZOMATO.NS", "name": "Zomato"},
    {"symbol": "PAYTM.NS", "name": "Paytm"},
    {"symbol": "IEX.NS", "name": "Indian Energy Exchange"},
    {"symbol": "IRCTC.NS", "name": "IRCTC"},
    {"symbol": "CDSL.NS", "name": "CDSL"},
    {"symbol": "BSE.NS", "name": "BSE Limited"},
    {"symbol": "TATAPOWER.NS", "name": "Tata Power"},
    {"symbol": "VEDL.NS", "name": "Vedanta"},
    {"symbol": "JIOFIN.NS", "name": "Jio Financial Services"},
    {"symbol": "VBL.NS", "name": "Varun Beverages"},
]
