INDIAN_STOCKS = [
    # Verified Heavyweights & Liquid NIFTY Tickers
    {"symbol": "RELIANCE.NS", "name": "Reliance Industries"},
    {"symbol": "TCS.NS", "name": "Tata Consultancy Services"},
    {"symbol": "HDFCBANK.NS", "name": "HDFC Bank"},
    {"symbol": "INFY.NS", "name": "Infosys"},
    {"symbol": "ICICIBANK.NS", "name": "ICICI Bank"},
    {"symbol": "HINDUNILVR.NS", "name": "Hindustan Unilever"},
    {"symbol": "SBIN.NS", "name": "State Bank of India"},
    {"symbol": "BHARTIARTL.NS", "name": "Bharti Airtel"},
    {"symbol": "ITC.NS", "name": "ITC Limited"},
    {"symbol": "KOTAKBANK.NS", "name": "Kotak Mahindra Bank"},
    {"symbol": "LT.NS", "name": "Larsen & Toubro"},
    {"symbol": "AXISBANK.NS", "name": "Axis Bank"},
    {"symbol": "MARUTI.NS", "name": "Maruti Suzuki"},
    {"symbol": "ULTRACEMCO.NS", "name": "UltraTech Cement"},
    {"symbol": "ASIANPAINT.NS", "name": "Asian Paints"},
    {"symbol": "SUNPHARMA.NS", "name": "Sun Pharmaceutical"},
    {"symbol": "TITAN.NS", "name": "Titan Company"},
    {"symbol": "HCLTECH.NS", "name": "HCL Technologies"},
    {"symbol": "BAJFINANCE.NS", "name": "Bajaj Finance"},
    {"symbol": "NTPC.NS", "name": "NTPC Limited"},
    {"symbol": "POWERGRID.NS", "name": "Power Grid Corporation"},
    {"symbol": "TATASTEEL.NS", "name": "Tata Steel"},
    {"symbol": "ADANIENT.NS", "name": "Adani Enterprises"},
    {"symbol": "ADANIPORTS.NS", "name": "Adani Ports"},
    {"symbol": "WIPRO.NS", "name": "Wipro"},
    {"symbol": "ONGC.NS", "name": "ONGC"},
    {"symbol": "JSWSTEEL.NS", "name": "JSW Steel"},
    {"symbol": "M&M.NS", "name": "Mahindra & Mahindra"},
    {"symbol": "COALINDIA.NS", "name": "Coal India"},
    {"symbol": "BAJAJ-AUTO.NS", "name": "Bajaj Auto"},
    {"symbol": "BPCL.NS", "name": "Bharat Petroleum"},
    {"symbol": "BRITANNIA.NS", "name": "Britannia Industries"},
    {"symbol": "CIPLA.NS", "name": "Cipla"},
    {"symbol": "DIVISLAB.NS", "name": "Divi's Laboratories"},
    {"symbol": "DRREDDY.NS", "name": "Dr. Reddy's Laboratories"},
    {"symbol": "EICHERMOT.NS", "name": "Eicher Motors"},
    {"symbol": "GRASIM.NS", "name": "Grasim Industries"},
    {"symbol": "HEROMOTOCO.NS", "name": "Hero MotoCorp"},
    {"symbol": "INDUSINDBK.NS", "name": "IndusInd Bank"},
    {"symbol": "HDFCLIFE.NS", "name": "HDFC Life Insurance"},
    {"symbol": "SBILIFE.NS", "name": "SBI Life Insurance"},
    {"symbol": "NESTLEIND.NS", "name": "Nestle India"},
    {"symbol": "APOLLOHOSP.NS", "name": "Apollo Hospitals"},
    {"symbol": "HINDALCO.NS", "name": "Hindalco Industries"},
    {"symbol": "TECHM.NS", "name": "Tech Mahindra"},

    # High Volume & Verified NSE Tickers
    {"symbol": "PAYTM.NS", "name": "Paytm (One97 Communications)"},
    {"symbol": "JIOFIN.NS", "name": "Jio Financial Services"},
    {"symbol": "SUZLON.NS", "name": "Suzlon Energy"},
    {"symbol": "IRCTC.NS", "name": "IRCTC"},
    {"symbol": "TATAPOWER.NS", "name": "Tata Power"},
    {"symbol": "VEDL.NS", "name": "Vedanta"},
    {"symbol": "VBL.NS", "name": "Varun Beverages"},
    {"symbol": "HAL.NS", "name": "Hindustan Aeronautics Limited"},
    {"symbol": "BEL.NS", "name": "Bharat Electronics Limited"},
    {"symbol": "RECLTD.NS", "name": "REC Limited"},
    {"symbol": "PFC.NS", "name": "Power Finance Corporation"},
    {"symbol": "IRFC.NS", "name": "Indian Railway Finance Corp"},
    {"symbol": "RVNL.NS", "name": "Rail Vikas Nigam Limited"},
    {"symbol": "TATAELXSI.NS", "name": "Tata Elxsi"},
    {"symbol": "TRENT.NS", "name": "Trent Limited"},
    {"symbol": "GAIL.NS", "name": "GAIL (India)"},
    {"symbol": "IOC.NS", "name": "Indian Oil Corporation"},
    {"symbol": "DLF.NS", "name": "DLF Limited"},
    {"symbol": "GODREJPROP.NS", "name": "Godrej Properties"},
    {"symbol": "OBEROIRLTY.NS", "name": "Oberoi Realty"},
    {"symbol": "PIDILITIND.NS", "name": "Pidilite Industries"},
    {"symbol": "SIEMENS.NS", "name": "Siemens India"},
    {"symbol": "ABB.NS", "name": "ABB India"},
    {"symbol": "HAVELLS.NS", "name": "Havells India"},
    {"symbol": "POLYCAB.NS", "name": "Polycab India"},
    {"symbol": "CDSL.NS", "name": "Central Depository Services"},
    {"symbol": "BSE.NS", "name": "BSE Limited"},
    {"symbol": "IEX.NS", "name": "Indian Energy Exchange"},
    {"symbol": "MCX.NS", "name": "Multi Commodity Exchange"},
    {"symbol": "BHEL.NS", "name": "Bharat Heavy Electricals"},
    {"symbol": "NHPC.NS", "name": "NHPC Limited"},
    {"symbol": "SJVN.NS", "name": "SJVN Limited"},
    {"symbol": "PNB.NS", "name": "Punjab National Bank"},
    {"symbol": "BANKBARODA.NS", "name": "Bank of Baroda"},
    {"symbol": "CANBK.NS", "name": "Canara Bank"},
    {"symbol": "IDFCFIRSTB.NS", "name": "IDFC First Bank"},
    {"symbol": "FEDERALBNK.NS", "name": "Federal Bank"},
    {"symbol": "BANDHANBNK.NS", "name": "Bandhan Bank"},
    {"symbol": "AUROPHARMA.NS", "name": "Aurobindo Pharma"},
    {"symbol": "LUPIN.NS", "name": "Lupin Limited"},
    {"symbol": "MANKIND.NS", "name": "Mankind Pharma"},
    {"symbol": "ZYDUSLIFE.NS", "name": "Zydus Lifesciences"},
    {"symbol": "TORNTPHARM.NS", "name": "Torrent Pharmaceuticals"},
    {"symbol": "MAXHEALTH.NS", "name": "Max Healthcare"},
    {"symbol": "PERSISTENT.NS", "name": "Persistent Systems"},
    {"symbol": "COFORGE.NS", "name": "Coforge Limited"},
    {"symbol": "MPHASIS.NS", "name": "Mphasis Limited"},
    {"symbol": "KPITTECH.NS", "name": "KPIT Technologies"},
    {"symbol": "TATACOMM.NS", "name": "Tata Communications"},
    {"symbol": "VOLTAS.NS", "name": "Voltas Limited"},
    {"symbol": "DIXON.NS", "name": "Dixon Technologies"},
    {"symbol": "COLPAL.NS", "name": "Colgate-Palmolive India"},
    {"symbol": "DABUR.NS", "name": "Dabur India"},
    {"symbol": "MARICO.NS", "name": "Marico Limited"},
    {"symbol": "GODREJCP.NS", "name": "Godrej Consumer Products"},
    {"symbol": "BERGEPAINT.NS", "name": "Berger Paints"},
    {"symbol": "MOTHERSON.NS", "name": "Samvardhana Motherson"},
    {"symbol": "BOSCHLTD.NS", "name": "Bosch Limited"},
    {"symbol": "BALKRISIND.NS", "name": "Balkrishna Industries"},
    {"symbol": "MRF.NS", "name": "MRF Limited"},
    {"symbol": "TIINDIA.NS", "name": "Tube Investments of India"},
    {"symbol": "TATAINVEST.NS", "name": "Tata Investment Corporation"},
    {"symbol": "ADANIPOWER.NS", "name": "Adani Power"},
    {"symbol": "ADANIGREEN.NS", "name": "Adani Green Energy"},
    {"symbol": "ATGL.NS", "name": "Adani Total Gas"},
    {"symbol": "AWL.NS", "name": "Adani Wilmar"},
    {"symbol": "IDEA.NS", "name": "Vodafone Idea"},
    {"symbol": "YESBANK.NS", "name": "Yes Bank"},
    {"symbol": "NYKAA.NS", "name": "FSN E-Commerce (Nykaa)"},
    {"symbol": "POLICYBZR.NS", "name": "PB Fintech (PolicyBazaar)"},
    {"symbol": "DELHIVERY.NS", "name": "Delhivery Limited"},
    {"symbol": "DMART.NS", "name": "Avenue Supermarts (DMart)"},
]
